export default {

  'item.document.de': 'Dokument',
  'item.document.fr': 'Document',
  'item.note.de': 'Notiz',
  'item.note.fr': 'Note',
  'item.label.de': 'Überschrift',
  'item.label.fr': 'Titre',
  'item.arrow.de': 'Pfeil',
  'item.arrow.fr': 'Flèche',

  'label.shared_workspace.de': 'Gemeinsamer Arbeitsbereich',
  'label.shared_workspace.fr': 'Espace de travail commun',
  'label.discussion.de': 'Diskussionsbeiträge',
  'label.discussion.fr': 'Contributions à la discussion',
  'label.document_discussion.de': 'Diskussion zu Dokument',
  'label.document_discussion.fr': 'Discussion sur le document',
  'label.document_name.de': 'Dokument Name',
  'label.document_name.fr': 'Nom du document',
  'label.file.de': 'Datei',
  'label.file.fr': 'Fichier',
  'label.new_comment.de': 'Neuer Kommentar',
  'label.new_comment.fr': 'Nouveau commentaire',
  'label.new_note.de': 'Neue Notiz',
  'label.new_note.fr': 'Nouvelle Note',
  'label.new_label.de': 'Neue Überschrift',
  'label.new_label.fr': 'Nouveau Titre',

  'action.submit.de': 'OK',
  'action.submit.fr': 'OK',
  'action.cancel.de': 'Abbrechen',
  'action.cancel.fr': 'Annuler',
  'action.reply.de': 'Antworten',
  'action.reply.fr': 'Réponse',
  'action.edit.de': 'Ändern',
  'action.edit.fr': 'Éditer',
  'action.delete.de': 'Löschen',
  'action.delete.fr': 'Supprimer',
  'action.attach_files.de': 'Dateien anhängen',
  'action.attach_files.fr': 'Joindre des fichiers',

  'warning.delete.de': 'Sie sind im Begriff dieses Objekt zu löschen',
  'warning.delete.fr': 'Vous êtes sur le point de supprimer cet objet',
  'warning.delete_comment.de': 'Sie sind im Begriff diesen Kommentar zu löschen',
  'warning.delete_comment.fr': 'Vous êtes sur le point de supprimer ce commentaire'
}
