export default {

  'item.document.de': 'Dokument',
  'item.document.fr': 'Document',
  'item.note.de': 'Notiz',
  'item.note.fr': 'Note',
  'item.label.de': 'Überschrift',
  'item.label.fr': 'Titre',
  'item.arrow.de': 'Pfeil',
  'item.arrow.fr': 'Flèche',

  'label.shared_workspace.de': 'Gemeinsamer Arbeitsbereich',
  'label.shared_workspace.fr': 'Espace de travail commun',
  'label.discussion.de': 'Diskussion',
  'label.discussion.fr': 'Discussion',
  'label.document_name.de': 'Dokument Name',
  'label.document_name.fr': 'Nom du document',
  'label.file.de': 'Datei',
  'label.file.fr': 'Fichier',
  'label.new_comment.de': 'Neuer Kommentar',
  'label.new_comment.fr': 'Nouveau commentaire',
  'label.new_note.de': 'Neue Notiz',
  'label.new_note.fr': 'Nouvelle Note',
  'label.new_label.de': 'Neue Überschrift',
  'label.new_label.fr': 'Nouveau Titre',

  'button.submit.de': 'OK',
  'button.submit.fr': 'OK',
  'button.reply.de': 'Antworten',
  'button.reply.fr': 'Réponse',
  'button.edit.de': 'Ändern',
  'button.edit.fr': 'Éditer',
  'button.delete.de': 'Löschen',
  'button.delete.fr': 'Supprimer',
  'button.attach_files.de': 'Dateien anhängen',
  'button.attach_files.fr': 'Joindre des fichiers',

  'warning.deletion.de': 'Sie sind im Begriff dieses Objekt zu löschen!',
  'warning.deletion.fr': 'Vous êtes sur le point de supprimer cet objet!'
}
