export default {
  'header.shared_workspace.de': 'Gemeinsamer Arbeitsbereich',
  'header.shared_workspace.fr': 'Espace de travail commun',
  'new.document.de': 'Dokument',
  'new.document.fr': 'Document',
  'new.note.de': 'Notiz',
  'new.note.fr': 'Note',
  'new.label.de': 'Beschriftung',
  'new.label.fr': 'Étiquetage',
  'note.new_note.de': 'Neue Notiz',
  'note.new_note.fr': 'Nouvelle note',
  'label.new_label.de': 'Neue Beschriftung',
  'label.new_label.fr': 'Nouveau étiquetage',
  'discussion.heading.de': 'Diskussion',
  'discussion.heading.fr': 'Discussion',
  'discussion.new_comment.de': 'Neuer Kommentar',
  'discussion.new_comment.fr': 'Nouveau commentaire',
  'global.submit.de': 'OK',
  'global.submit.fr': 'OK'
}
