export default {

  'item.document.de': 'Dokument',
  'item.document.fr': 'Document',
  'item.note.de': 'Notiz',
  'item.note.fr': 'Note',
  'item.label.de': 'Überschrift',
  'item.label.fr': 'Titre',
  'item.arrow.de': 'Pfeil',
  'item.arrow.fr': 'Flèche',

  'label.shared_workspace.de': 'Gemeinsamer Arbeitsbereich',
  'label.shared_workspace.fr': 'Espace de travail commun',
  'label.admin_workspaces.de': 'Workspaces und Mitglieder',
  'label.admin_workspaces.fr': 'Espaces de travail et membres',
  'label.admin_users.de': 'Benutzer und Mitgliedschaften',
  'label.admin_users.fr': 'Utilisateurs et affiliations',
  'label.no_workspaces.de': 'Keine Workspaces vorhanden',
  'label.no_workspaces.fr': 'Aucun espace de travail disponible',
  'label.discussion.de': 'Diskussionsbeiträge',
  'label.discussion.fr': 'Contributions à la discussion',
  'label.document_filter.de': 'Filter auf Dokument:',
  'label.document_filter.fr': 'Filtre sur document:',
  'label.document_name.de': 'Dokument Name',
  'label.document_name.fr': 'Nom du document',
  'label.file.de': 'Datei',
  'label.file.fr': 'Fichier',
  'label.new_comment.de': 'Neuer Diskussionsbeitrag',
  'label.new_comment.fr': 'Nouvel article de discussion',
  'label.new_note.de': 'Neue Notiz',
  'label.new_note.fr': 'Nouvelle Note',
  'label.new_label.de': 'Neue Überschrift',
  'label.new_label.fr': 'Nouveau Titre',
  'label.new_workspace.de': 'Neuer Workspace',
  'label.new_workspace.fr': 'Nouvel espace de travail',
  'label.workspace_name.de': 'Name',
  'label.workspace_name.fr': 'Nom',

  'action.submit.de': 'OK',
  'action.submit.fr': 'OK',
  'action.cancel.de': 'Abbrechen',
  'action.cancel.fr': 'Annuler',
  'action.reply.de': 'Antworten',
  'action.reply.fr': 'Réponse',
  'action.edit.de': 'Ändern',
  'action.edit.fr': 'Éditer',
  'action.delete.de': 'Löschen',
  'action.delete.fr': 'Supprimer',
  'action.attach_files.de': 'Dateien anhängen',
  'action.attach_files.fr': 'Joindre des fichiers',
  'action.add_workspace.de': 'Workspace hinuzfügen',
  'action.add_workspace.fr': 'Ajouter un espace de travail',

  'warning.delete.de': 'Sie sind im Begriff dieses Objekt zu löschen',
  'warning.delete.fr': 'Vous êtes sur le point de supprimer cet objet',
  'warning.delete_comment.de': 'Sie sind im Begriff diesen Kommentar zu löschen',
  'warning.delete_comment.fr': 'Vous êtes sur le point de supprimer ce commentaire'
}
