import legal from './legal'

export default {

  'item.document.de': 'Dokument',
  'item.document.fr': 'Document',
  'item.note.de': 'Notiz',
  'item.note.fr': 'Note',
  'item.textblock.de': 'Textblock',
  'item.textblock.fr': 'Bloc de texte',
  'item.label.de': 'Überschrift',
  'item.label.fr': 'Titre',
  'item.arrow.de': 'Pfeil',
  'item.arrow.fr': 'Flèche',

  'label.welcome.de': 'Online Kollaborationsplattform',
  'label.welcome.fr': 'Plate-forme de collaboration en ligne',
  'label.login.de': 'Login',
  'label.login.fr': 'Login',
  'label.forgot_password.de': 'Aktuelles Passwort vergessen?',
  'label.forgot_password.fr': 'Mot de passe actuel oublié?',
  'label.reset_password.de': 'Passwort zurücksetzen',
  'label.reset_password.fr': 'Réinitialiser le mot de passe',
  'label.email_sent.de': 'Email erfolgreich gesendet',
  'label.email_sent.fr': 'Email envoyé avec succès',
  'label.to.de': 'an',
  'label.to.fr': 'à',
  'label.user_profile.de': 'Benutzerprofil',
  'label.user_profile.fr': 'Profil d\'utilisateur',
  'label.show_email_address.de': 'Emailadresse anderen Nutzern zeigen',
  'label.show_email_address.fr': 'Montrer son adresse e-mail aux autres utilisateurs',
  'label.privacy.de': 'Privacy',
  'label.privacy.fr': 'Vie privée',
  'label.imprint.de': 'Impressum',
  'label.imprint.fr': 'Impressum',
  'label.privacy_policy.de': 'Datenschutz',
  'label.privacy_policy.fr': 'Protection des données',
  'label.shared_workspace.de': 'Gemeinsamer Arbeitsbereich',
  'label.shared_workspace.fr': 'Espace de travail commun',
  'label.admin.de': 'Online Kollaborationsplattform - Verwaltung',
  'label.admin.fr': 'Plate-forme de collaboration en ligne - Administration',
  'label.admin_workspaces.de': 'Arbeitsbereiche und Mitglieder',
  'label.admin_workspaces.fr': 'Espaces de travail et membres',
  'label.admin_users.de': 'Benutzer und Mitgliedschaften',
  'label.admin_users.fr': 'Utilisateurs et affiliations',
  'label.no_workspaces.de': 'Keine Arbeitsbereiche vorhanden',
  'label.no_workspaces.fr': 'Aucun espace de travail disponible',
  'label.discussion.de': 'Diskussion',
  'label.discussion.fr': 'Discussion',
  'label.no_comments.de': 'Noch keine Diskussionsbeiträge.<br>Machen Sie den Anfang!',
  'label.no_comments.fr': 'Aucune contribution.<br>Lancez-vous!',
  'label.document_filter.de': 'nach Dokument gefiltert',
  'label.document_filter.fr': 'filtré par document',
  'label.textblock_filter.de': 'nach Textblock gefiltert',
  'label.textblock_filter.fr': 'filtré par bloc de texte',
  'label.document_name.de': 'Dokument Name',
  'label.document_name.fr': 'Nom du document',
  'label.file.de': 'Datei',
  'label.file.fr': 'Fichier',
  'label.translation.de': 'Übersetzung',
  'label.translation.fr': 'Traduction',
  'label.translation_edited.de': 'Übersetzung bearbeitet',
  'label.translation_edited.fr': 'Traduction éditée',
  'label.automatic.de': 'automatisch',
  'label.automatic.fr': 'automatique',
  'label.edited.de': 'bearbeitet',
  'label.edited.fr': 'édité',
  'label.none.de': 'keine',
  'label.none.fr': 'pas de',
  'label.new_comment.de': 'Neuer Beitrag',
  'label.new_comment.fr': 'Nouvelle contribution',
  'label.new_comment_document.de': 'Neuer Beitrag zum Dokument',
  'label.new_comment_document.fr': 'Nouvelle contribution au document',
  'label.new_comment_textblock.de': 'Neuer Beitrag zum Textblock',
  'label.new_comment_textblock.fr': 'Nouvelle contribution au bloc de texte',
  'label.new_note.de': 'Neue Notiz',
  'label.new_note.fr': 'Nouvelle Note',
  'label.new_textblock.de': 'Neuer Textblock',
  'label.new_textblock.fr': 'Nouveau bloc de texte',
  'label.new_label.de': 'Neue Überschrift',
  'label.new_label.fr': 'Nouveau Titre',
  'label.new_workspace.de': 'Neuer Arbeitsbereich',
  'label.new_workspace.fr': 'Nouvel espace de travail',
  'label.new_user.de': 'Neuer Benutzer',
  'label.new_user.fr': 'Nouvel utilisateur',
  'label.edit_workspace.de': 'Arbeitsbereich bearbeiten',
  'label.edit_workspace.fr': 'Modifier l\'espace de travail',
  'label.edit_user.de': 'Benutzer bearbeiten',
  'label.edit_user.fr': 'Modifier l\'utilisateur',
  'label.edit_memberships.de': 'Mitglieder verwalten',
  'label.edit_memberships.fr': 'Gérer les membres',
  'label.edit_affiliations.de': 'Mitgliedschaften verwalten',
  'label.edit_affiliations.fr': 'Gérer les affiliations',
  'label.workspace.de': 'Workspace',
  'label.workspace.fr': 'Espace de travail',
  'label.owner.de': 'Eigentümer',
  'label.owner.fr': 'Propriétaire',
  'label.user.de': 'Benutzer',
  'label.user.fr': 'Utilisateur',
  'label.active.de': 'Aktiv',
  'label.active.fr': 'Actif',
  'label.member.de': 'Mitglied',
  'label.member.fr': 'Membre',
  'label.editor.de': 'Editor',
  'label.editor.fr': 'Éditeur',
  'label.workspace_name.de': 'Name',
  'label.workspace_name.fr': 'Nom',
  'label.display_name.de': 'Name',
  'label.display_name.fr': 'Nom',
  'label.email_address.de': 'Email',
  'label.email_address.fr': 'E-mail',
  'label.password.de': 'Passwort',
  'label.password.fr': 'Mot de passe',
  'label.color.de': 'Farbe',
  'label.color.fr': 'Couleur',
  'label.search.de': 'Suche',
  'label.search.fr': 'Recherche',
  'label.of.de': 'von',
  'label.of.fr': 'de',
  'label.warning.de': 'Warnung',
  'label.warning.fr': 'Avertissement',

  'action.submit.de': 'OK',
  'action.submit.fr': 'OK',
  'action.cancel.de': 'Abbrechen',
  'action.cancel.fr': 'Annuler',
  'action.reply.de': 'Antworten',
  'action.reply.fr': 'Réponse',
  'action.create.de': 'Erstellen',
  'action.create.fr': 'Créer',
  'action.edit.de': 'Ändern',
  'action.edit.fr': 'Éditer',
  'action.lock.de': 'Verriegeln',
  'action.lock.fr': 'Verrouiller',
  'action.unlock.de': 'Entriegeln',
  'action.unlock.fr': 'Déverrouiller',
  'action.delete.de': 'Löschen',
  'action.delete.fr': 'Supprimer',
  'action.delete_many.de': '${} Objekte löschen',
  'action.delete_many.fr': 'Supprimer ${} objets',
  'action.download.de': 'Download',
  'action.download.fr': 'Télécharger',
  'action.translate.de': 'Übersetzen',
  'action.translate.fr': 'Traduire',
  'action.set_zoom.de': 'Aktuellen Zoom-Wert speichern',
  'action.set_zoom.fr': 'Enregistrer la valeur actuelle du zoom',
  'action.add_workspace.de': 'Arbeitsbereich hinzufügen',
  'action.add_workspace.fr': 'Ajouter un espace de travail',
  'action.add_user.de': 'Benutzer hinzufügen',
  'action.add_user.fr': 'Ajouter un utilisateur',
  'action.show_workspace.de': 'Arbeitsbereich anzeigen',
  'action.show_workspace.fr': 'Afficher l\'espace de travail',
  'action.edit_workspace.de': 'Arbeitsbereich bearbeiten',
  'action.edit_workspace.fr': 'Modifier l\'espace de travail',
  'action.edit_memberships.de': 'Mitglieder verwalten',
  'action.edit_memberships.fr': 'Gérer les membres',
  'action.edit_user.de': 'Benutzer bearbeiten',
  'action.edit_user.fr': 'Modifier l\'utilisateur',
  'action.edit_affiliations.de': 'Mitgliedschaften verwalten',
  'action.edit_affiliations.fr': 'Gérer les affiliations',
  'action.delete_workspace.de': 'Arbeitsbereich löschen',
  'action.delete_workspace.fr': 'Supprimer l\'espace de travail',
  'action.delete_user.de': 'Benutzer löschen',
  'action.delete_user.fr': 'Supprimer l\'utilisateur',
  'action.reset_password.de': 'Passwort zurücksetzen',
  'action.reset_password.fr': 'Réinitialiser le mot de passe',
  'action.change_password.de': 'Passwort ändern',
  'action.change_password.fr': 'Modifier le mot de passe',

  'tooltip.add.de': 'Element hinzufügen',
  'tooltip.add.fr': 'Ajouter un élément',
  'tooltip.home.de': 'Startbereich anzeigen',
  'tooltip.home.fr': 'Retour à la zone de départ',
  'tooltip.zoom_to_fit.de': 'gesamten Arbeitsbereich anzeigen',
  'tooltip.zoom_to_fit.fr': 'Afficher tout l\'espace de travail',
  'tooltip.zoom_in.de': 'größer zoomen',
  'tooltip.zoom_in.fr': 'zoomer',
  'tooltip.zoom_out.de': 'kleiner zoomen',
  'tooltip.zoom_out.fr': 'zoomer plus petit',
  'tooltip.discuss.de': 'Diskussion anzeigen',
  'tooltip.discuss.fr': 'Afficher la discussion',
  'tooltip.submit.de': 'Beitrag absenden',
  'tooltip.submit.fr': 'Publier la contribution',
  'tooltip.reply.de': 'Antworten',
  'tooltip.reply.fr': 'Répondre',
  'tooltip.translate.de': 'Übersetzen',
  'tooltip.translate.fr': 'Traduire',
  'tooltip.attach.de': 'Dateien anhängen',
  'tooltip.attach.fr': 'Joindre des fichiers',
  'tooltip.reset_filter.de': 'Filter entfernen',
  'tooltip.reset_filter.fr': 'Supprimer le filtre',
  'tooltip.open_panel.de': 'Diskussion aufklappen',
  'tooltip.open_panel.fr': 'Ouvrir la discussion',
  'tooltip.close_panel.de': 'Diskussion zuklappen',
  'tooltip.close_panel.fr': 'Fermer la discussion',
  'tooltip.open_fullscreen.de': 'Dokument in Vollbild-Ansicht anzeigen',
  'tooltip.open_fullscreen.fr': 'Afficher le document en plein écran',
  'tooltip.close_fullscreen.de': 'Arbeitsbereich anzeigen',
  'tooltip.close_fullscreen.fr': 'Afficher l\'espace de travail',
  'tooltip.select_workspace.de': 'Arbeitsbereich wechseln',
  'tooltip.select_workspace.fr': 'Changer d\'espace de travail',
  'tooltip.select_language.de': 'Sprache auswählen',
  'tooltip.select_language.fr': 'Choisir la langue',
  'tooltip.admin.de': 'Verwaltung',
  'tooltip.admin.fr': 'Administration',

  'warning.delete.de': 'Sie sind im Begriff dieses Objekt zu löschen',
  'warning.delete.fr': 'Vous êtes sur le point de supprimer cet objet',
  'warning.delete_many.de': 'Sie sind im Begriff ${} Objekte zu löschen',
  'warning.delete_many.fr': 'Vous êtes sur le point de supprimer des ${} objets',
  'warning.delete_comment.de': 'Sie sind im Begriff diesen Kommentar zu löschen',
  'warning.delete_comment.fr': 'Vous êtes sur le point de supprimer ce commentaire',
  'warning.delete_workspace.de': 'Sie sind im Begriff diesen Arbeitsbereich zu löschen',
  'warning.delete_workspace.fr': 'Vous êtes sur le point de supprimer cet espace de travail',
  'warning.delete_user.de': 'Sie sind im Begriff diesen Benutzer zu löschen',
  'warning.delete_user.fr': 'Vous êtes sur le point de supprimer cet utilisateur',
  'warning.translation_failed.de': 'Automatische Übersetzung fehlgeschlagen',
  'warning.translation_failed.fr': 'Échec de la traduction automatique',
  'warning.translation_confirm.de': `Deine Eingabe konnte nicht übersetzt werden. Klicke "Abbrechen", um weiter zu
    editieren oder "Erstellen", um ohne Übersetzung zu speichern. Tipp: Wähle nach dem Erstellen "Ändern", um eine
    Übersetzung hinzuzufügen.`,
  'warning.translation_confirm.fr': `Ta saisie n'a pas pu être traduite. Clique sur "Annuler" pour continuer à éditer
    ou sur "Créer" pour enregistrer sans traduction. Conseil: après la création, choisis "Éditer" pour ajouter une
    traduction.`,
  'warning.translation_alert.de': `Deine Eingabe konnte nicht übersetzt werden.`,
  'warning.translation_alert.fr': `Ta saisie n'a pas pu être traduite.`,

  ...legal
}
